# Generated by Django 4.2 on 2024-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdAndHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(blank=True, null=True, verbose_name='是谁的')),
                ('hand', models.BooleanField(blank=True, null=True, verbose_name='手')),
                ('elbow', models.BooleanField(blank=True, null=True, verbose_name='肘')),
                ('palm', models.BooleanField(blank=True, null=True, verbose_name='手心')),
                ('prothorax', models.BooleanField(blank=True, null=True, verbose_name='前胸背心')),
                ('Lumbosacral', models.BooleanField(blank=True, null=True, verbose_name='腰骶')),
                ('foot', models.BooleanField(blank=True, null=True, verbose_name='足')),
                ('Knee', models.BooleanField(blank=True, null=True, verbose_name='膝')),
                ('Foot_heart', models.BooleanField(blank=True, null=True, verbose_name='足心')),
                ('body', models.BooleanField(blank=True, null=True, verbose_name='身体')),
                ('Alvine', models.BooleanField(blank=True, null=True, verbose_name='小腹')),
            ],
        ),
        migrations.CreateModel(
            name='HeadNoseMouth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(blank=True, null=True, verbose_name='是谁的')),
                ('headache', models.BooleanField(blank=True, default=False, null=True, verbose_name='头疼')),
                ('head_itch', models.BooleanField(blank=True, default=False, null=True, verbose_name='头痒')),
                ('dizzy', models.BooleanField(blank=True, default=False, null=True, verbose_name='头晕')),
                ('heavy_head', models.BooleanField(blank=True, default=False, null=True, verbose_name='头重')),
                ('nasal_congestion', models.BooleanField(blank=True, default=False, null=True, verbose_name='鼻塞')),
                ('nose_itch', models.BooleanField(blank=True, default=False, null=True, verbose_name='鼻痒')),
                ('dry_nose', models.BooleanField(blank=True, default=False, null=True, verbose_name='鼻干')),
                ('clear_discharge', models.BooleanField(blank=True, default=False, null=True, verbose_name='流清涕')),
                ('thick_discharge', models.BooleanField(blank=True, default=False, null=True, verbose_name='流浊涕')),
                ('nosebleed', models.BooleanField(blank=True, default=False, null=True, verbose_name='流鼻血')),
                ('anosmia', models.BooleanField(blank=True, default=False, null=True, verbose_name='鼻不闻香臭')),
                ('dry_mouth', models.BooleanField(blank=True, default=False, null=True, verbose_name='口干')),
                ('bitter_taste', models.BooleanField(blank=True, default=False, null=True, verbose_name='口苦')),
                ('bland_taste', models.BooleanField(blank=True, default=False, null=True, verbose_name='口淡')),
                ('ulcers', models.BooleanField(blank=True, default=False, null=True, verbose_name='口腔溃疡')),
                ('swollen_gums', models.BooleanField(blank=True, default=False, null=True, verbose_name='牙龈肿痛')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(blank=True, null=True, verbose_name='是谁的')),
                ('Shortness', models.BooleanField(blank=True, default=False, null=True, verbose_name='气短难言')),
                ('fatigue_easily', models.BooleanField(blank=True, default=False, null=True, verbose_name='容易疲劳')),
                ('heavy_legs', models.BooleanField(blank=True, default=False, null=True, verbose_name='腿沉重')),
                ('weakness_legs', models.BooleanField(blank=True, default=False, null=True, verbose_name='腿无力')),
                ('weakness', models.BooleanField(blank=True, default=False, null=True, verbose_name='浑身无力')),
            ],
        ),
        migrations.CreateModel(
            name='Sweat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.IntegerField(blank=True, null=True, verbose_name='是谁的')),
                ('spontaneous_sweat', models.SmallIntegerField(blank=True, choices=[(1, '无'), (2, '有')], null=True, verbose_name='自汗')),
                ('night_sweat', models.SmallIntegerField(blank=True, choices=[(1, '无'), (2, '有')], null=True, verbose_name='盗汗')),
                ('hot_flashes', models.SmallIntegerField(blank=True, choices=[(1, '无'), (2, '有')], null=True, verbose_name='潮热汗')),
                ('chest_sweat', models.SmallIntegerField(blank=True, choices=[(1, '无'), (2, '有')], null=True, verbose_name='前胸汗')),
                ('back_sweat', models.SmallIntegerField(blank=True, choices=[(1, '无'), (2, '有')], null=True, verbose_name='背心汗')),
                ('other_sweat', models.TextField(blank=True, null=True, verbose_name='其他')),
            ],
        ),
    ]
