# Generated by Django 4.2 on 2024-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldandhot',
            name='Alvine',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='小腹'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='Foot_heart',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='足心'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='Knee',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='膝'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='Lumbosacral',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='腰骶'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='body',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='身体'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='elbow',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='肘'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='foot',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='足'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='hand',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='手'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='palm',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='手心'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='prothorax',
            field=models.SmallIntegerField(blank=True, choices=[(1, '冷'), (2, '热')], null=True, verbose_name='前胸背心'),
        ),
    ]
