# Generated by Django 4.2 on 2024-06-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0007_alter_bowelandurinarysymptoms_belong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20, verbose_name='是谁的')),
                ('anion_pulse_late', models.BooleanField(blank=True, null=True, verbose_name='阴脉迟')),
                ('anion_pulse_se', models.BooleanField(blank=True, null=True, verbose_name='阴脉涩')),
                ('anion_pulse_wei', models.BooleanField(blank=True, null=True, verbose_name='阴脉微')),
                ('anion_pulse_huan', models.BooleanField(blank=True, null=True, verbose_name='阴脉缓')),
                ('anion_pulse_lao', models.BooleanField(blank=True, null=True, verbose_name='阴脉牢')),
                ('anion_pulse_ruo', models.BooleanField(blank=True, null=True, verbose_name='阴脉弱')),
                ('anion_pulse_san', models.BooleanField(blank=True, null=True, verbose_name='阴脉散')),
                ('anion_pulse_jie', models.BooleanField(blank=True, null=True, verbose_name='阴脉结')),
                ('anion_pulse_dai', models.BooleanField(blank=True, null=True, verbose_name='阴脉代')),
                ('cation_pulse_shu', models.BooleanField(blank=True, null=True, verbose_name='阳脉数')),
                ('cation_pulse_hua', models.BooleanField(blank=True, null=True, verbose_name='阳脉滑')),
                ('cation_pulse_hong', models.BooleanField(blank=True, null=True, verbose_name='阳脉洪')),
                ('cation_pulse_jin', models.BooleanField(blank=True, null=True, verbose_name='阳脉紧')),
                ('cation_pulse_xian', models.BooleanField(blank=True, null=True, verbose_name='阳脉弦')),
                ('cation_pulse_ru', models.BooleanField(blank=True, null=True, verbose_name='阳脉濡')),
                ('cation_pulse_xi', models.BooleanField(blank=True, null=True, verbose_name='阳脉细')),
                ('cation_pulse_cu', models.BooleanField(blank=True, null=True, verbose_name='阳脉促')),
                ('cation_pulse_da', models.BooleanField(blank=True, null=True, verbose_name='阳脉大')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='其他补充')),
            ],
        ),
    ]
