# Generated by Django 4.2 on 2024-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0008_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowelandurinarysymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='coldandhot',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='currentmedicalhistory',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='dietcondition',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='gynecologicalsymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='headnosemouth',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='numbnesssymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='physicalstrength',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='pulse',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='result',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='sleepdisorder',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='sweat',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='thirst',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='tongueappearance',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='urologicalsymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
        migrations.AddField(
            model_name='westernmedicinediagnosis',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='修改说明'),
        ),
    ]
