# Generated by Django 4.2 on 2024-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info', '0009_bowelandurinarysymptoms_change_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowelandurinarysymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='coldandhot',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='currentmedicalhistory',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='dietcondition',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='gynecologicalsymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='headnosemouth',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='numbnesssymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='physicalstrength',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='处方修改说明'),
        ),
        migrations.AlterField(
            model_name='result',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='sleepdisorder',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='sweat',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='thirst',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='tongueappearance',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='urologicalsymptoms',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
        migrations.AlterField(
            model_name='westernmedicinediagnosis',
            name='change_notes',
            field=models.TextField(blank=True, null=True, verbose_name='本次信息的修改说明'),
        ),
    ]
