# Generated by Django 4.2 on 2024-07-09 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, verbose_name='医生名称')),
                ('user_name', models.CharField(max_length=30, verbose_name='患者名称')),
                ('photo_path', models.CharField(blank=True, default='static/loginAndRegister/img/default.png', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('check_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.checkpeople', verbose_name='监管确认')),
                ('crawl_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.crawlpeople', verbose_name='抓药师')),
            ],
        ),
    ]
