# Generated by Django 4.2 on 2024-07-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpharmacy',
            name='photo_path',
            field=models.CharField(blank=True, default='pharmacy_image/default.png', max_length=100, null=True),
        ),
    ]
