# Generated by Django 4.2 on 2024-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_userpharmacy_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpharmacy',
            name='prescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpharmacy',
            name='symptom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
