# Generated by Django 4.2 on 2024-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_userpharmacy_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpharmacy',
            name='belong',
            field=models.BigIntegerField(default=1, verbose_name='归属'),
        ),
    ]
