# Generated by Django 4.2 on 2024-06-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=30)),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctorInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, verbose_name='账户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('photo_path', models.CharField(blank=True, default='static/loginAndRegister/img/default.png', max_length=100, null=True)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True, verbose_name='医院')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介(选填)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_and_select.department', verbose_name='科室')),
            ],
        ),
    ]
