# Generated by Django 4.2 on 2024-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0002_alter_userinfo_age_alter_userinfo_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='身高(m)'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='体重(Kg)'),
        ),
    ]
