# Generated by Django 4.2 on 2024-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0003_userinfo_high_userinfo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
    ]
