# Generated by Django 4.2 on 2024-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0004_alter_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
