# Generated by Django 4.2 on 2024-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegister', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first',
            field=models.BooleanField(default=False, verbose_name='第一次诊断'),
        ),
    ]
