# Generated by Django 4.2 on 2024-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info_new', '0002_currentmedicalhistory_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowMangBig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20, verbose_name='是谁的')),
                ('bowel_movements_frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='大便天一次？')),
            ],
        ),
        migrations.CreateModel(
            name='HowMangSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20, verbose_name='是谁的')),
                ('nocturia_frequency', models.CharField(blank=True, max_length=20, null=True, verbose_name='一夜排尿次？（夜尿情况）')),
            ],
        ),
        migrations.CreateModel(
            name='HowNightAwake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20, verbose_name='是谁的')),
                ('wake_up_time_at_night', models.CharField(blank=True, max_length=20, null=True, verbose_name='夜间醒在点钟？')),
            ],
        ),
        migrations.CreateModel(
            name='HowNightSleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20, verbose_name='是谁的')),
                ('sleep_time_at_night', models.CharField(blank=True, max_length=20, null=True, verbose_name='夜间点钟睡？')),
            ],
        ),
        migrations.DeleteModel(
            name='OtherSymptoms',
        ),
    ]
