# Generated by Django 4.2 on 2024-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info_new', '0005_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='TEST',
        ),
        migrations.AddField(
            model_name='table',
            name='bleedingSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='出血情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='bowelAndFlatulenceSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='大便及排气情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='coldSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您身体的某个部位经常冰凉的情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='coughSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您咳嗽吐痰的情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='dietSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您的饮食情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='emotionalSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您的情绪情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='facialSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='五官？'),
        ),
        migrations.AddField(
            model_name='table',
            name='habitSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='习惯？'),
        ),
        migrations.AddField(
            model_name='table',
            name='heatSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您身体的某个部位经常感觉发热的情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='howMangBig',
            field=models.TextField(blank=True, null=True, verbose_name='大便一天几次？'),
        ),
        migrations.AddField(
            model_name='table',
            name='howMangSmall',
            field=models.TextField(blank=True, null=True, verbose_name='一夜排尿几次？（夜尿情况）'),
        ),
        migrations.AddField(
            model_name='table',
            name='howNightAwake',
            field=models.TextField(blank=True, null=True, verbose_name='夜间醒在几点钟？'),
        ),
        migrations.AddField(
            model_name='table',
            name='howNightSleep',
            field=models.TextField(blank=True, null=True, verbose_name='夜间几点钟睡？'),
        ),
        migrations.AddField(
            model_name='table',
            name='hydrationSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您的饮水情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='oralSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='口中感受？'),
        ),
        migrations.AddField(
            model_name='table',
            name='painSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='有无疼痛感觉（痛的部位）？'),
        ),
        migrations.AddField(
            model_name='table',
            name='physicalSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='体力情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='sleepSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='睡眠情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='sweatingSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='您平时的出汗情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='table',
            name='urinationSymptoms',
            field=models.TextField(blank=True, null=True, verbose_name='小便情况？'),
        ),
        migrations.AddField(
            model_name='table',
            name='windAndCold',
            field=models.TextField(blank=True, null=True, verbose_name='您感觉怕风怕冷的情况？'),
        ),
    ]
