# Generated by Django 4.2 on 2024-08-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_info_new', '0006_remove_table_test_table_bleedingsymptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='medicine',
            field=models.TextField(blank=True, null=True, verbose_name='处方'),
        ),
    ]
